Repository Selecro/Selecro-webovky, pull requests merged in 2023-03, with the labels that each got.

#108 Refresh page
  package-lock.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/pages/navody/navody.component.ts
  src/app/pages/pomucky/pomucky.component.ts
  src/app/pages/vyukovymod/vyukovymod.component.ts
  src/favicon.ico
  tsconfig.json
Labels: enhancement

#114 Obrazky navody
  src/app/app-routing.module.ts
  src/app/app.component.css
  src/app/app.component.html
  src/app/app.component.ts
  src/app/pages/navody/navody-detail/navody-detail.component.html
  src/app/pages/navody/navody.component.html
  src/app/pages/navody/navody.component.ts
  src/app/pages/pomucky/pomucky.component.html
  src/app/service/navody.service.ts
  src/app/service/pomucky.service.ts
  src/app/service/vyuka.service.ts
  src/app/types/navod.ts
  src/assets/icon/chapadla-harold.jpg
  src/assets/icon/chapadla-harold2.jpg
  src/assets/icon/chobotnicka.jpg
  src/assets/icon/dinosaurus.jpg
  src/assets/icon/doplnky-harold.jpg
  src/assets/icon/harold.jpg
  src/assets/icon/hlava-dinosaura.jpg
  src/assets/icon/hlava-harold.jpg
  src/assets/icon/hlava-zelva.jpg
  src/assets/icon/horni-cast-krunyre-zelva.jpg
  src/assets/icon/nos-dinosaura.jpg
  src/assets/icon/ocas-dinosaura.jpg
  src/assets/icon/ocasek-zelva.jpg
  src/assets/icon/osten-dinosaura.jpg
  src/assets/icon/predni-noha-dinosaura.jpg
  src/assets/icon/predni-ploutev-zelva.jpg
  src/assets/icon/spodni-cast-krunyre-zelva.jpg
  src/assets/icon/telo-dinosaura.jpg
  src/assets/icon/uzavreni-harold.jpg
  src/assets/icon/vyplneni-harold.jpg
  src/assets/icon/zadni-noha-dinosaura.jpg
  src/assets/icon/zadni-ploutev-zelva.jpg
Labels: enhancement, invalid, review requested

#118 Dev
  src/app/app-routing.module.ts
  src/app/app.component.css
  src/app/app.component.html
  src/app/app.component.ts
  src/app/pages/navody/navody-detail/navody-detail.component.css
  src/app/pages/navody/navody-detail/navody-detail.component.html
  src/app/pages/navody/navody.component.html
  src/app/pages/navody/navody.component.ts
  src/app/pages/pomucky/pomucky.component.html
  src/app/service/navody.service.ts
  src/app/service/pomucky.service.ts
  src/app/service/vyuka.service.ts
  src/app/types/navod.ts
  src/assets/icon/chapadla-harold.jpg
  src/assets/icon/chapadla-harold2.jpg
  src/assets/icon/chobotnicka.jpg
  src/assets/icon/dinosaurus.jpg
  src/assets/icon/doplnky-harold.jpg
  src/assets/icon/harold.jpg
  src/assets/icon/hlava-dinosaura.jpg
  src/assets/icon/hlava-harold.jpg
  src/assets/icon/hlava-zelva.jpg
  src/assets/icon/horni-cast-krunyre-zelva.jpg
  src/assets/icon/nos-dinosaura.jpg
  src/assets/icon/ocas-dinosaura.jpg
  src/assets/icon/ocasek-zelva.jpg
  src/assets/icon/osten-dinosaura.jpg
  src/assets/icon/predni-noha-dinosaura.jpg
  src/assets/icon/predni-ploutev-zelva.jpg
  src/assets/icon/spodni-cast-krunyre-zelva.jpg
  src/assets/icon/telo-dinosaura.jpg
  src/assets/icon/uzavreni-harold.jpg
  src/assets/icon/vyplneni-harold.jpg
  src/assets/icon/zadni-noha-dinosaura.jpg
  src/assets/icon/zadni-ploutev-zelva.jpg
Labels: review requested

#119 buttons responzivita
  src/app/pages/navody/navody-detail/navody-detail.component.css
  src/app/pages/navody/navody-detail/navody-detail.component.html
Labels: review requested

#120 Cross-realm object access in Webpack 5
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/safe.pipe.ts
  tsconfig.json
Labels: dependencies, review requested

#122 add package-lock.json
  .github/workflows/main.yml
  .gitignore
  .htaccess
  angular.json
  package-lock.json
  tsconfig.json
Labels: enhancement, dependencies, review requested

#126 remove duplicate body+html, edit glabol css
  src/app/app.component.css
  src/app/app.component.html
  src/index.html
Labels: enhancement, review requested
